"""init

Revision ID: 2ff02eb71a67
Revises: a718f7ce8844
Create Date: 2020-12-01 14:00:34.195127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ff02eb71a67'
down_revision = 'a718f7ce8844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_day', sa.Column('Schedule_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'study_day', 'schedule', ['Schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_day', type_='foreignkey')
    op.drop_column('study_day', 'Schedule_id')
    # ### end Alembic commands ###
