"""init

Revision ID: 42855d23bc2e
Revises: 4dc52721814c
Create Date: 2020-12-02 16:25:52.983429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42855d23bc2e'
down_revision = '4dc52721814c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
