"""init

Revision ID: 4dba2ecc5994
Revises: 2ff02eb71a67
Create Date: 2020-12-01 14:11:06.651778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4dba2ecc5994'
down_revision = '2ff02eb71a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_class', sa.Column('Schedule_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'study_class', 'schedule', ['Schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_class', type_='foreignkey')
    op.drop_column('study_class', 'Schedule_id')
    # ### end Alembic commands ###
