"""init

Revision ID: a718f7ce8844
Revises: a5f5f582ba72
Create Date: 2020-12-01 13:54:14.147632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a718f7ce8844'
down_revision = 'a5f5f582ba72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_day', sa.Column('Schedule_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'study_day', 'schedule', ['Schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_day', type_='foreignkey')
    op.drop_column('study_day', 'Schedule_id')
    # ### end Alembic commands ###
