"""add user model

Revision ID: b72cc2116f8b
Revises: 42855d23bc2e
Create Date: 2020-12-11 11:13:11.268188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b72cc2116f8b'
down_revision = '42855d23bc2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookie',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_by_name', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('updated_by_name', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('deleted_by_name', sa.String(), nullable=True),
    sa.Column('student_code', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('cookie', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cookie_created_at'), 'cookie', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cookie_created_at'), table_name='cookie')
    op.drop_table('cookie')
    # ### end Alembic commands ###
